baseurl = "www.example.com"
title = "Example"
theme ="hugo-theme-basic"
languageCode = "en-us"
googleAnalytics = ""
copyright = "© 2016-19 Example"

[params]
  titleEmoji = "🎉"
  twitter = "exampleHandle"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "blog/"
  

[[params.menu]]
  name = "about"
  url = "page/about-hugo"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true