baseurl = "https://www.example.com"
title = "Example Site"
theme ="hugo-theme-basic"
languageCode = "en-us"
googleAnalytics = ""
enableEmoji = true 
copyright = "© 2016-19 Example Site Author"

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"

[params]
  titleEmoji = ":tada:"
  twitter = "exampleHandle"

[Permalinks]
  post = "post/:slug"

[[params.menu]]
  name = "blog"
  url = "blog/"

[[params.menu]]
  name = "post series"
  url = "series/"
  

[[params.menu]]
  name = "about"
  url = "page/about-hugo"
  

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    respectDoNotTrack = true
    useSessionStorage = true
  [privacy.twitter]
    enableDNT = true
  [privacy.youtube]
    privacyEnhanced = true